### ISSUE TITLE
libskkを使ったSKK実装で辞書を使用できない

### ISSUE THREAD

**Issue by lonsagisawa** [project-brightblue/skk-dict-imascg#1]
## 再現方法

Ubuntuの場合libskk-devのインストールが必要。

```
$ echo "O g a t a c h i e r i SPC" | skk -f /PATH/TO/DICT/SKK-JISYO.imascgss.fullname
```
## 試した修正

libskkが吐いたエラーを見て辞書に

```
;; okuri-ari entries.
```

を加えた。エラーは消えたが依然変換はできない。

**Comment by mlny** [comment]
libskkを使っている実装ではEUC版の辞書を使ってください。

**Comment by lonsagisawa** [comment]
辞書の文字コードをEUCにしました。これで使えるはず。

**Comment by lonsagisawa** [comment]
👍

![screenshot from 2016-09-08 01-40-14](https://cloud.githubusercontent.com/assets/5173607/18320931/e1cc4fa2-7566-11e6-966d-964361f31d0e.png)
