### ISSUE TITLE
下の名前の辞書

### ISSUE THREAD

**Issue by rinsuki** [project-brightblue/skk-dict-imascg#12]
デフォルト辞書だと変換できなくてつらい例

![out](https://user-images.githubusercontent.com/6533808/32145202-df51e3c4-bd07-11e7-8e5c-7e3d8b5c0a39.gif)

フルネームで変換して自前で登録しろと言われればその通りですが、あったほうが便利だと思いますので、お手空きのときによければ検討していただけるとありがたいです。

**Comment by lonsagisawa** [comment]
わかりづらいですが、SKK-JISYO.imascg.firstnameが下の名前の辞書です。そちらをAquaSKKに登録してください。

# Workaround
わかりにくいので、どの辞書がどんな辞書なのかわかるようにREADMEの改修を行います。

**Comment by rinsuki** [comment]
解決しました！
ありがとうございます。
